// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260122155021_RemoveRoleAndUserRoleMappingEntities")]
    partial class RemoveRoleAndUserRoleMappingEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AnswerOption", b =>
                {
                    b.Property<Guid>("AnswerOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("AnswerOptionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("AnswerOptions");
                });

            modelBuilder.Entity("Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("RejectReason")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Domain.Entities.Enrollment", b =>
                {
                    b.Property<Guid>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("Domain.Entities.GradedAttempt", b =>
                {
                    b.Property<Guid>("GradedAttemptId")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("GradedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GradedItemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Score")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("GradedAttemptId");

                    b.HasIndex("UserId");

                    b.ToTable("GradedAttempts");
                });

            modelBuilder.Entity("Domain.Entities.GradedItem", b =>
                {
                    b.Property<Guid>("GradedItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAutoGraded")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxScore")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("GradedItemId");

                    b.HasIndex("LessonId");

                    b.ToTable("GradedItems");
                });

            modelBuilder.Entity("Domain.Entities.Lesson", b =>
                {
                    b.Property<Guid>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("EstimatedMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("Index")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGraded")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("LessonId");

                    b.HasIndex("ModuleId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("Domain.Entities.Module", b =>
                {
                    b.Property<Guid>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("ModuleId");

                    b.HasIndex("CourseId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<int>("Method")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("PaymentId");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<Guid>("GradedItemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<decimal>("Points")
                        .HasColumnType("numeric");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("QuestionId");

                    b.HasIndex("GradedItemId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Domain.Entities.QuestionSubmission", b =>
                {
                    b.Property<Guid>("QuestionSubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnswerText")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("FileUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("GradedAttemptId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAutoGraded")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Score")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("QuestionSubmissionId");

                    b.HasIndex("GradedAttemptId");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionSubmissions");
                });

            modelBuilder.Entity("Domain.Entities.SubmissionAnswerOption", b =>
                {
                    b.Property<Guid>("SubmissionAnswerOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnswerOptionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionSubmissionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Weight")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(1m);

                    b.HasKey("SubmissionAnswerOptionId");

                    b.HasIndex("AnswerOptionId");

                    b.HasIndex("QuestionSubmissionId");

                    b.ToTable("SubmissionAnswerOptions");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerfied")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 22, 15, 50, 19, 854, DateTimeKind.Utc).AddTicks(9767),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Email = "Student1@gmail.com",
                            FullName = "Student1",
                            IsDeleted = false,
                            IsVerfied = true,
                            PasswordHash = new byte[] { 21, 235, 95, 93, 39, 14, 75, 198, 64, 106, 23, 115, 251, 218, 157, 161, 42, 155, 192, 244, 73, 97, 63, 140, 39, 24, 180, 246, 159, 53, 43, 217, 128, 71, 129, 2, 178, 253, 208, 100, 62, 64, 8, 66, 131, 237, 109, 60, 242, 101, 145, 167, 136, 218, 252, 17, 35, 108, 215, 36, 167, 225, 247, 26 },
                            PasswordSalt = new byte[] { 138, 73, 0, 161, 62, 100, 163, 132, 136, 199, 176, 253, 121, 62, 8, 6, 197, 27, 200, 178, 147, 170, 106, 21, 160, 115, 154, 234, 208, 123, 134, 124, 244, 202, 66, 45, 126, 128, 229, 119, 195, 214, 58, 47, 36, 238, 137, 3, 36, 163, 143, 24, 70, 252, 68, 65, 179, 131, 25, 143, 19, 254, 120, 176, 65, 167, 46, 197, 28, 120, 167, 39, 115, 243, 240, 69, 147, 86, 133, 200, 102, 65, 186, 97, 53, 56, 237, 169, 192, 85, 2, 50, 130, 224, 4, 43, 140, 184, 178, 144, 37, 241, 252, 177, 60, 15, 225, 138, 125, 186, 98, 128, 71, 208, 77, 63, 28, 19, 90, 148, 59, 241, 169, 135, 45, 82, 66, 9 },
                            Role = 0
                        },
                        new
                        {
                            UserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 1, 22, 15, 50, 19, 854, DateTimeKind.Utc).AddTicks(9773),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Email = "Student2@gmail.com",
                            FullName = "Student2",
                            IsDeleted = false,
                            IsVerfied = true,
                            PasswordHash = new byte[] { 163, 124, 213, 223, 134, 59, 200, 187, 97, 134, 82, 24, 95, 24, 55, 197, 176, 94, 175, 82, 5, 216, 65, 66, 16, 99, 46, 243, 1, 4, 129, 221, 236, 240, 104, 31, 125, 64, 236, 141, 6, 166, 200, 70, 147, 92, 6, 173, 136, 59, 152, 17, 177, 72, 220, 104, 221, 55, 26, 28, 234, 172, 74, 128 },
                            PasswordSalt = new byte[] { 61, 178, 164, 20, 193, 33, 188, 65, 110, 106, 110, 176, 245, 37, 29, 63, 162, 14, 47, 152, 240, 195, 204, 109, 47, 207, 20, 64, 190, 118, 63, 139, 21, 8, 32, 35, 120, 185, 212, 242, 121, 62, 103, 22, 163, 59, 241, 230, 235, 206, 189, 5, 51, 86, 182, 54, 228, 125, 213, 105, 209, 138, 32, 32, 217, 134, 29, 208, 145, 243, 18, 82, 9, 123, 196, 58, 241, 181, 24, 109, 245, 137, 84, 155, 108, 58, 39, 221, 172, 199, 80, 151, 128, 103, 191, 74, 62, 219, 192, 143, 243, 110, 94, 200, 184, 93, 174, 96, 6, 172, 131, 171, 93, 129, 23, 26, 151, 159, 111, 164, 53, 22, 7, 98, 173, 43, 169, 155 },
                            Role = 0
                        },
                        new
                        {
                            UserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 1, 22, 15, 50, 19, 854, DateTimeKind.Utc).AddTicks(9775),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Email = "Employer@gmail.com",
                            FullName = "Instructor",
                            IsDeleted = false,
                            IsVerfied = true,
                            PasswordHash = new byte[] { 164, 74, 96, 80, 40, 138, 19, 45, 59, 109, 178, 214, 227, 113, 131, 222, 241, 162, 38, 140, 171, 169, 114, 126, 26, 153, 8, 61, 115, 156, 53, 53, 210, 86, 233, 109, 157, 118, 218, 194, 78, 68, 78, 105, 221, 208, 106, 91, 135, 135, 164, 220, 234, 82, 157, 237, 108, 50, 251, 121, 247, 217, 249, 231 },
                            PasswordSalt = new byte[] { 151, 213, 87, 53, 169, 126, 193, 6, 193, 166, 14, 53, 93, 148, 232, 26, 162, 166, 20, 225, 209, 69, 120, 89, 104, 158, 76, 86, 212, 222, 201, 156, 186, 101, 187, 45, 19, 61, 2, 202, 249, 213, 211, 143, 132, 136, 254, 178, 15, 53, 72, 180, 136, 102, 239, 149, 165, 20, 92, 4, 118, 67, 135, 219, 138, 221, 200, 59, 190, 191, 184, 142, 231, 221, 123, 187, 181, 18, 19, 130, 107, 30, 58, 194, 129, 226, 110, 106, 199, 185, 188, 94, 252, 22, 118, 70, 93, 248, 67, 44, 128, 129, 113, 1, 13, 190, 61, 21, 144, 9, 249, 147, 206, 108, 141, 49, 8, 15, 249, 89, 214, 61, 116, 178, 87, 216, 99, 171 },
                            Role = 0
                        },
                        new
                        {
                            UserId = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 1, 22, 15, 50, 19, 854, DateTimeKind.Utc).AddTicks(9777),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Email = "Admin@gmail.com",
                            FullName = "Admin",
                            IsDeleted = false,
                            IsVerfied = true,
                            PasswordHash = new byte[] { 30, 227, 159, 26, 167, 45, 104, 65, 136, 129, 161, 195, 111, 113, 211, 245, 201, 77, 243, 28, 59, 169, 102, 12, 118, 4, 190, 70, 202, 63, 12, 228, 21, 16, 164, 163, 56, 178, 83, 8, 237, 83, 252, 252, 35, 243, 174, 178, 23, 158, 224, 237, 93, 177, 17, 234, 195, 252, 129, 162, 48, 121, 18, 69 },
                            PasswordSalt = new byte[] { 199, 187, 100, 62, 34, 211, 229, 241, 9, 217, 176, 25, 181, 17, 3, 150, 106, 40, 169, 127, 179, 53, 85, 69, 199, 175, 108, 99, 113, 11, 239, 2, 228, 98, 105, 136, 186, 152, 132, 119, 174, 27, 147, 248, 85, 46, 186, 171, 36, 69, 71, 8, 221, 2, 226, 0, 134, 67, 90, 52, 231, 236, 41, 218, 171, 172, 47, 230, 172, 243, 247, 140, 136, 64, 79, 161, 151, 210, 75, 218, 34, 56, 123, 72, 44, 246, 30, 179, 145, 158, 21, 167, 78, 230, 220, 89, 29, 155, 11, 70, 207, 39, 112, 4, 150, 158, 183, 193, 175, 188, 238, 30, 7, 83, 246, 59, 20, 117, 43, 182, 142, 173, 69, 225, 238, 75, 103, 39 },
                            Role = 0
                        });
                });

            modelBuilder.Entity("Domain.Entities.AnswerOption", b =>
                {
                    b.HasOne("Domain.Entities.Question", "Question")
                        .WithMany("AnswerOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Domain.Entities.Enrollment", b =>
                {
                    b.HasOne("Domain.Entities.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Enrollments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.GradedAttempt", b =>
                {
                    b.HasOne("Domain.Entities.GradedItem", "GradedItem")
                        .WithMany("GradedAttempts")
                        .HasForeignKey("GradedAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("GradedAttempts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradedItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.GradedItem", b =>
                {
                    b.HasOne("Domain.Entities.Lesson", "Lesson")
                        .WithMany("GradedItems")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Domain.Entities.Lesson", b =>
                {
                    b.HasOne("Domain.Entities.Module", "Module")
                        .WithMany("Lessons")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Domain.Entities.Module", b =>
                {
                    b.HasOne("Domain.Entities.Course", "Course")
                        .WithMany("Modules")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Domain.Entities.Payment", b =>
                {
                    b.HasOne("Domain.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Question", b =>
                {
                    b.HasOne("Domain.Entities.GradedItem", "GradedItem")
                        .WithMany("Questions")
                        .HasForeignKey("GradedItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradedItem");
                });

            modelBuilder.Entity("Domain.Entities.QuestionSubmission", b =>
                {
                    b.HasOne("Domain.Entities.GradedAttempt", "GradedAttempt")
                        .WithMany("QuestionSubmissions")
                        .HasForeignKey("GradedAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Question", "Question")
                        .WithMany("QuestionSubmissions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GradedAttempt");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Domain.Entities.SubmissionAnswerOption", b =>
                {
                    b.HasOne("Domain.Entities.AnswerOption", "AnswerOption")
                        .WithMany("SubmissionAnswerOptions")
                        .HasForeignKey("AnswerOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.QuestionSubmission", "QuestionSubmission")
                        .WithMany("SelectedOptions")
                        .HasForeignKey("QuestionSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnswerOption");

                    b.Navigation("QuestionSubmission");
                });

            modelBuilder.Entity("Domain.Entities.AnswerOption", b =>
                {
                    b.Navigation("SubmissionAnswerOptions");
                });

            modelBuilder.Entity("Domain.Entities.Course", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Modules");
                });

            modelBuilder.Entity("Domain.Entities.GradedAttempt", b =>
                {
                    b.Navigation("QuestionSubmissions");
                });

            modelBuilder.Entity("Domain.Entities.GradedItem", b =>
                {
                    b.Navigation("GradedAttempts");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Domain.Entities.Lesson", b =>
                {
                    b.Navigation("GradedItems");
                });

            modelBuilder.Entity("Domain.Entities.Module", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("Domain.Entities.Question", b =>
                {
                    b.Navigation("AnswerOptions");

                    b.Navigation("QuestionSubmissions");
                });

            modelBuilder.Entity("Domain.Entities.QuestionSubmission", b =>
                {
                    b.Navigation("SelectedOptions");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("GradedAttempts");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
