// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AnswerOption", b =>
                {
                    b.Property<Guid>("AnswerOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("AnswerOptionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("AnswerOptions");
                });

            modelBuilder.Entity("Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("RejectReason")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Domain.Entities.Enrollment", b =>
                {
                    b.Property<Guid>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EnrolledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ProgressPercent")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("Domain.Entities.GradedAttempt", b =>
                {
                    b.Property<Guid>("GradedAttemptId")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("GradedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GradedItemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Score")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("GradedAttemptId");

                    b.HasIndex("UserId");

                    b.ToTable("GradedAttempts");
                });

            modelBuilder.Entity("Domain.Entities.GradedItem", b =>
                {
                    b.Property<Guid>("GradedItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAutoGraded")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxScore")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("GradedItemId");

                    b.HasIndex("LessonId");

                    b.ToTable("GradedItems");
                });

            modelBuilder.Entity("Domain.Entities.Lesson", b =>
                {
                    b.Property<Guid>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("EstimatedMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGraded")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("LessonId");

                    b.HasIndex("ModuleId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("Domain.Entities.LessonResource", b =>
                {
                    b.Property<Guid>("LessonResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<long?>("DurationInSeconds")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDownloadable")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int>("ResourceType")
                        .HasColumnType("integer");

                    b.Property<string>("ResourceUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("LessonResourceId");

                    b.HasIndex("LessonId");

                    b.ToTable("LessonResources");
                });

            modelBuilder.Entity("Domain.Entities.Module", b =>
                {
                    b.Property<Guid>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("ModuleId");

                    b.HasIndex("CourseId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("PaymentId");

                    b.HasIndex("CourseId");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<Guid>("GradedItemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<decimal>("Points")
                        .HasColumnType("numeric");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("QuestionId");

                    b.HasIndex("GradedItemId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Domain.Entities.QuestionSubmission", b =>
                {
                    b.Property<Guid>("QuestionSubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnswerText")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("FileUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("GradedAttemptId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAutoGraded")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Score")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("QuestionSubmissionId");

                    b.HasIndex("GradedAttemptId");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionSubmissions");
                });

            modelBuilder.Entity("Domain.Entities.SubmissionAnswerOption", b =>
                {
                    b.Property<Guid>("SubmissionAnswerOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnswerOptionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionSubmissionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Weight")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(1m);

                    b.HasKey("SubmissionAnswerOptionId");

                    b.HasIndex("AnswerOptionId");

                    b.HasIndex("QuestionSubmissionId");

                    b.ToTable("SubmissionAnswerOptions");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerfied")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 24, 10, 38, 30, 134, DateTimeKind.Utc).AddTicks(3353),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Email = "Student1@gmail.com",
                            FullName = "Student1",
                            IsDeleted = false,
                            IsVerfied = true,
                            PasswordHash = new byte[] { 7, 85, 7, 161, 35, 199, 22, 228, 75, 128, 44, 102, 6, 104, 122, 254, 1, 80, 138, 27, 58, 243, 179, 127, 123, 162, 29, 46, 104, 178, 159, 93, 247, 69, 73, 105, 13, 102, 127, 208, 32, 58, 201, 139, 87, 250, 154, 143, 90, 127, 31, 74, 38, 154, 81, 45, 112, 130, 220, 122, 59, 38, 19, 173 },
                            PasswordSalt = new byte[] { 155, 179, 51, 73, 203, 44, 238, 47, 147, 117, 128, 75, 101, 72, 38, 42, 63, 167, 103, 116, 134, 202, 241, 167, 56, 153, 114, 71, 160, 81, 110, 14, 80, 98, 151, 116, 233, 112, 197, 169, 84, 118, 245, 186, 140, 64, 200, 143, 232, 115, 121, 125, 171, 19, 164, 73, 91, 220, 178, 111, 194, 79, 192, 90, 45, 150, 114, 128, 128, 194, 74, 46, 77, 95, 15, 72, 139, 87, 94, 42, 241, 234, 223, 172, 171, 23, 91, 49, 235, 251, 158, 162, 178, 51, 216, 99, 216, 72, 203, 243, 243, 108, 135, 189, 131, 17, 147, 141, 68, 72, 77, 249, 191, 100, 187, 64, 36, 159, 21, 141, 48, 93, 234, 223, 211, 202, 2, 174 },
                            Role = 0
                        },
                        new
                        {
                            UserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 1, 24, 10, 38, 30, 134, DateTimeKind.Utc).AddTicks(3360),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Email = "Student2@gmail.com",
                            FullName = "Student2",
                            IsDeleted = false,
                            IsVerfied = true,
                            PasswordHash = new byte[] { 17, 155, 239, 21, 242, 217, 24, 12, 220, 129, 99, 191, 78, 123, 59, 120, 184, 15, 227, 76, 20, 139, 197, 201, 88, 227, 120, 60, 105, 190, 79, 4, 12, 204, 117, 156, 217, 114, 105, 86, 64, 75, 22, 60, 151, 143, 118, 98, 93, 177, 116, 24, 232, 166, 229, 86, 17, 163, 83, 74, 92, 159, 121, 194 },
                            PasswordSalt = new byte[] { 35, 109, 80, 189, 214, 150, 245, 189, 255, 211, 156, 105, 236, 89, 218, 83, 135, 48, 238, 117, 1, 66, 177, 98, 203, 242, 128, 204, 14, 233, 88, 255, 163, 76, 240, 199, 242, 199, 246, 35, 207, 149, 1, 229, 195, 149, 221, 10, 113, 48, 175, 167, 91, 218, 144, 25, 125, 180, 12, 133, 175, 210, 83, 174, 106, 16, 154, 107, 20, 97, 131, 154, 151, 196, 32, 103, 141, 23, 71, 139, 119, 161, 166, 217, 21, 168, 109, 63, 138, 30, 0, 231, 152, 172, 76, 213, 215, 145, 95, 212, 42, 192, 211, 13, 186, 80, 228, 49, 185, 183, 61, 199, 194, 195, 178, 209, 22, 151, 130, 198, 22, 178, 239, 214, 62, 192, 253, 169 },
                            Role = 0
                        },
                        new
                        {
                            UserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 1, 24, 10, 38, 30, 134, DateTimeKind.Utc).AddTicks(3362),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Email = "Employer@gmail.com",
                            FullName = "Instructor",
                            IsDeleted = false,
                            IsVerfied = true,
                            PasswordHash = new byte[] { 112, 213, 143, 217, 132, 108, 8, 93, 176, 91, 73, 253, 25, 14, 24, 215, 8, 218, 176, 243, 31, 15, 208, 212, 212, 191, 162, 161, 218, 131, 15, 244, 103, 71, 12, 128, 81, 28, 116, 71, 237, 201, 233, 184, 153, 146, 136, 41, 74, 247, 21, 60, 150, 46, 223, 102, 213, 8, 137, 24, 172, 138, 179, 252 },
                            PasswordSalt = new byte[] { 230, 30, 142, 155, 15, 215, 60, 170, 138, 159, 252, 161, 198, 170, 33, 69, 49, 5, 179, 16, 29, 132, 105, 48, 167, 89, 140, 91, 64, 233, 129, 114, 194, 20, 227, 118, 130, 211, 121, 114, 183, 221, 74, 216, 104, 99, 220, 218, 121, 125, 166, 208, 213, 84, 155, 147, 27, 80, 194, 147, 207, 18, 188, 164, 247, 88, 83, 50, 24, 181, 200, 14, 106, 155, 148, 129, 42, 60, 194, 254, 27, 104, 240, 134, 169, 62, 72, 75, 112, 127, 45, 239, 150, 87, 84, 34, 14, 102, 243, 189, 173, 160, 132, 139, 17, 123, 88, 219, 114, 221, 44, 234, 105, 29, 83, 103, 57, 186, 135, 23, 146, 44, 173, 77, 46, 1, 29, 135 },
                            Role = 0
                        },
                        new
                        {
                            UserId = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 1, 24, 10, 38, 30, 134, DateTimeKind.Utc).AddTicks(3364),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Email = "Admin@gmail.com",
                            FullName = "Admin",
                            IsDeleted = false,
                            IsVerfied = true,
                            PasswordHash = new byte[] { 32, 203, 47, 221, 59, 130, 102, 33, 217, 168, 222, 240, 247, 204, 251, 5, 2, 141, 100, 109, 17, 179, 112, 94, 24, 73, 196, 228, 159, 147, 29, 78, 218, 148, 244, 8, 76, 158, 62, 151, 57, 223, 80, 150, 209, 175, 43, 225, 147, 68, 137, 116, 76, 29, 30, 74, 144, 116, 219, 244, 64, 62, 29, 217 },
                            PasswordSalt = new byte[] { 38, 161, 222, 130, 21, 216, 158, 81, 123, 165, 29, 39, 219, 215, 172, 170, 155, 204, 104, 40, 239, 235, 124, 105, 174, 28, 137, 88, 112, 208, 239, 130, 215, 181, 29, 186, 1, 207, 215, 126, 230, 105, 72, 43, 123, 30, 55, 230, 140, 23, 186, 120, 143, 191, 186, 191, 71, 107, 211, 135, 118, 126, 125, 117, 49, 239, 103, 48, 210, 12, 125, 75, 144, 9, 236, 191, 94, 129, 208, 33, 177, 136, 121, 103, 149, 248, 81, 135, 41, 158, 221, 91, 104, 206, 194, 50, 165, 173, 154, 229, 1, 211, 164, 156, 136, 67, 175, 253, 151, 46, 31, 97, 217, 35, 15, 244, 29, 236, 47, 144, 62, 10, 107, 19, 59, 22, 142, 218 },
                            Role = 0
                        });
                });

            modelBuilder.Entity("Domain.Entities.UserLessonProgress", b =>
                {
                    b.Property<Guid>("LessonProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CompletionPercent")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastWatchedSecond")
                        .HasColumnType("integer");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LessonProgressId");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId");

                    b.ToTable("UserLessonProgresses");
                });

            modelBuilder.Entity("Domain.Entities.AnswerOption", b =>
                {
                    b.HasOne("Domain.Entities.Question", "Question")
                        .WithMany("AnswerOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Domain.Entities.Enrollment", b =>
                {
                    b.HasOne("Domain.Entities.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Enrollments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.GradedAttempt", b =>
                {
                    b.HasOne("Domain.Entities.GradedItem", "GradedItem")
                        .WithMany("GradedAttempts")
                        .HasForeignKey("GradedAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("GradedAttempts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradedItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.GradedItem", b =>
                {
                    b.HasOne("Domain.Entities.Lesson", "Lesson")
                        .WithMany("GradedItems")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Domain.Entities.Lesson", b =>
                {
                    b.HasOne("Domain.Entities.Module", "Module")
                        .WithMany("Lessons")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Domain.Entities.LessonResource", b =>
                {
                    b.HasOne("Domain.Entities.Lesson", "Lesson")
                        .WithMany("LessonResources")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Domain.Entities.Module", b =>
                {
                    b.HasOne("Domain.Entities.Course", "Course")
                        .WithMany("Modules")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Domain.Entities.Payment", b =>
                {
                    b.HasOne("Domain.Entities.Course", "Course")
                        .WithMany("Payments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Enrollment", "Enrollment")
                        .WithMany("Payments")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Enrollment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Question", b =>
                {
                    b.HasOne("Domain.Entities.GradedItem", "GradedItem")
                        .WithMany("Questions")
                        .HasForeignKey("GradedItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradedItem");
                });

            modelBuilder.Entity("Domain.Entities.QuestionSubmission", b =>
                {
                    b.HasOne("Domain.Entities.GradedAttempt", "GradedAttempt")
                        .WithMany("QuestionSubmissions")
                        .HasForeignKey("GradedAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Question", "Question")
                        .WithMany("QuestionSubmissions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GradedAttempt");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Domain.Entities.SubmissionAnswerOption", b =>
                {
                    b.HasOne("Domain.Entities.AnswerOption", "AnswerOption")
                        .WithMany("SubmissionAnswerOptions")
                        .HasForeignKey("AnswerOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.QuestionSubmission", "QuestionSubmission")
                        .WithMany("SelectedOptions")
                        .HasForeignKey("QuestionSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnswerOption");

                    b.Navigation("QuestionSubmission");
                });

            modelBuilder.Entity("Domain.Entities.UserLessonProgress", b =>
                {
                    b.HasOne("Domain.Entities.Lesson", "Lesson")
                        .WithMany("UserLessonProgresses")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("UserLessonProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.AnswerOption", b =>
                {
                    b.Navigation("SubmissionAnswerOptions");
                });

            modelBuilder.Entity("Domain.Entities.Course", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Modules");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Domain.Entities.Enrollment", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Domain.Entities.GradedAttempt", b =>
                {
                    b.Navigation("QuestionSubmissions");
                });

            modelBuilder.Entity("Domain.Entities.GradedItem", b =>
                {
                    b.Navigation("GradedAttempts");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Domain.Entities.Lesson", b =>
                {
                    b.Navigation("GradedItems");

                    b.Navigation("LessonResources");

                    b.Navigation("UserLessonProgresses");
                });

            modelBuilder.Entity("Domain.Entities.Module", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("Domain.Entities.Question", b =>
                {
                    b.Navigation("AnswerOptions");

                    b.Navigation("QuestionSubmissions");
                });

            modelBuilder.Entity("Domain.Entities.QuestionSubmission", b =>
                {
                    b.Navigation("SelectedOptions");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("GradedAttempts");

                    b.Navigation("Payments");

                    b.Navigation("UserLessonProgresses");
                });
#pragma warning restore 612, 618
        }
    }
}
