// <auto-generated />
using System;
using Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Repositories.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260123090442_AddLessonResourceEntity")]
    partial class AddLessonResourceEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AnswerOption", b =>
                {
                    b.Property<Guid>("AnswerOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("AnswerOptionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("AnswerOptions");
                });

            modelBuilder.Entity("Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("RejectReason")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Domain.Entities.Enrollment", b =>
                {
                    b.Property<Guid>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EnrolledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ProgressPercent")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("Domain.Entities.GradedAttempt", b =>
                {
                    b.Property<Guid>("GradedAttemptId")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("GradedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GradedItemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Score")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("GradedAttemptId");

                    b.HasIndex("UserId");

                    b.ToTable("GradedAttempts");
                });

            modelBuilder.Entity("Domain.Entities.GradedItem", b =>
                {
                    b.Property<Guid>("GradedItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAutoGraded")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxScore")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("GradedItemId");

                    b.HasIndex("LessonId");

                    b.ToTable("GradedItems");
                });

            modelBuilder.Entity("Domain.Entities.Lesson", b =>
                {
                    b.Property<Guid>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("EstimatedMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGraded")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("LessonId");

                    b.HasIndex("ModuleId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("Domain.Entities.LessonResource", b =>
                {
                    b.Property<Guid>("LessonResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<long?>("DurationInSeconds")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDownloadable")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int>("ResourceType")
                        .HasColumnType("integer");

                    b.Property<string>("ResourceUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("LessonResourceId");

                    b.HasIndex("LessonId");

                    b.ToTable("LessonResources");
                });

            modelBuilder.Entity("Domain.Entities.Module", b =>
                {
                    b.Property<Guid>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("ModuleId");

                    b.HasIndex("CourseId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EnrollmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("PaymentId");

                    b.HasIndex("CourseId");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<Guid>("GradedItemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<decimal>("Points")
                        .HasColumnType("numeric");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("QuestionId");

                    b.HasIndex("GradedItemId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Domain.Entities.QuestionSubmission", b =>
                {
                    b.Property<Guid>("QuestionSubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnswerText")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("FileUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("GradedAttemptId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAutoGraded")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Score")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("QuestionSubmissionId");

                    b.HasIndex("GradedAttemptId");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionSubmissions");
                });

            modelBuilder.Entity("Domain.Entities.SubmissionAnswerOption", b =>
                {
                    b.Property<Guid>("SubmissionAnswerOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnswerOptionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionSubmissionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Weight")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(1m);

                    b.HasKey("SubmissionAnswerOptionId");

                    b.HasIndex("AnswerOptionId");

                    b.HasIndex("QuestionSubmissionId");

                    b.ToTable("SubmissionAnswerOptions");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerfied")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 23, 9, 4, 40, 338, DateTimeKind.Utc).AddTicks(8356),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Email = "Student1@gmail.com",
                            FullName = "Student1",
                            IsDeleted = false,
                            IsVerfied = true,
                            PasswordHash = new byte[] { 120, 198, 62, 161, 82, 205, 186, 139, 113, 19, 11, 254, 202, 194, 208, 145, 188, 95, 30, 219, 129, 104, 255, 238, 7, 185, 71, 8, 202, 3, 46, 47, 77, 193, 130, 172, 246, 211, 23, 190, 248, 225, 167, 147, 154, 218, 184, 239, 36, 148, 221, 107, 18, 78, 119, 216, 51, 14, 39, 133, 36, 57, 2, 246 },
                            PasswordSalt = new byte[] { 59, 165, 22, 115, 110, 143, 185, 183, 75, 113, 71, 73, 134, 84, 9, 71, 12, 174, 171, 153, 227, 106, 211, 154, 236, 62, 98, 133, 117, 127, 43, 38, 144, 186, 127, 157, 8, 231, 176, 174, 184, 31, 52, 37, 193, 108, 7, 105, 39, 101, 215, 3, 12, 197, 247, 211, 220, 163, 171, 234, 120, 164, 220, 197, 136, 225, 248, 30, 151, 56, 54, 53, 72, 246, 113, 197, 110, 87, 247, 60, 182, 142, 9, 45, 135, 161, 52, 34, 112, 18, 208, 134, 170, 88, 239, 184, 245, 30, 38, 248, 166, 157, 165, 90, 232, 246, 161, 87, 174, 3, 109, 64, 142, 66, 114, 75, 216, 184, 90, 55, 98, 112, 139, 54, 114, 82, 109, 125 },
                            Role = 0
                        },
                        new
                        {
                            UserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 1, 23, 9, 4, 40, 338, DateTimeKind.Utc).AddTicks(8362),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Email = "Student2@gmail.com",
                            FullName = "Student2",
                            IsDeleted = false,
                            IsVerfied = true,
                            PasswordHash = new byte[] { 70, 208, 222, 87, 173, 234, 152, 51, 201, 80, 137, 246, 207, 248, 147, 191, 107, 194, 164, 186, 244, 22, 81, 247, 115, 53, 227, 188, 169, 42, 172, 147, 114, 25, 27, 88, 239, 194, 78, 164, 129, 130, 94, 9, 107, 245, 160, 192, 54, 202, 76, 114, 246, 64, 216, 10, 182, 214, 27, 242, 89, 70, 163, 0 },
                            PasswordSalt = new byte[] { 168, 188, 132, 79, 243, 93, 38, 219, 39, 152, 126, 216, 137, 16, 76, 141, 105, 201, 207, 228, 171, 230, 176, 248, 238, 102, 238, 176, 98, 21, 41, 86, 122, 218, 21, 139, 25, 66, 210, 161, 9, 67, 163, 233, 244, 94, 222, 163, 215, 45, 233, 112, 1, 187, 155, 132, 7, 158, 169, 45, 144, 3, 185, 239, 115, 34, 154, 235, 43, 253, 25, 248, 138, 220, 200, 35, 52, 155, 148, 204, 47, 45, 248, 127, 159, 33, 192, 32, 138, 224, 241, 177, 94, 213, 35, 253, 100, 215, 116, 189, 244, 105, 24, 6, 68, 135, 153, 156, 209, 47, 57, 66, 197, 205, 108, 134, 208, 16, 28, 233, 147, 37, 174, 12, 45, 248, 150, 36 },
                            Role = 0
                        },
                        new
                        {
                            UserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 1, 23, 9, 4, 40, 338, DateTimeKind.Utc).AddTicks(8364),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Email = "Employer@gmail.com",
                            FullName = "Instructor",
                            IsDeleted = false,
                            IsVerfied = true,
                            PasswordHash = new byte[] { 35, 196, 50, 0, 229, 245, 192, 254, 2, 11, 164, 29, 167, 7, 214, 221, 194, 115, 73, 167, 12, 172, 14, 105, 134, 163, 175, 151, 32, 107, 74, 89, 228, 108, 55, 173, 206, 193, 162, 199, 158, 11, 214, 218, 50, 141, 216, 231, 62, 225, 137, 236, 250, 119, 124, 1, 252, 174, 240, 56, 19, 25, 63, 154 },
                            PasswordSalt = new byte[] { 218, 180, 51, 156, 233, 61, 49, 181, 209, 24, 31, 187, 222, 43, 38, 70, 3, 105, 248, 182, 198, 69, 218, 46, 13, 117, 6, 63, 142, 230, 50, 217, 192, 74, 109, 136, 245, 162, 37, 118, 19, 129, 185, 3, 8, 89, 115, 85, 23, 236, 104, 131, 71, 110, 128, 218, 7, 56, 85, 240, 164, 246, 245, 118, 150, 193, 245, 127, 87, 231, 126, 89, 189, 56, 196, 221, 77, 97, 131, 83, 233, 99, 70, 14, 146, 99, 49, 45, 240, 176, 47, 176, 127, 67, 11, 105, 221, 198, 152, 55, 139, 132, 230, 114, 156, 102, 151, 143, 179, 101, 226, 134, 64, 93, 237, 75, 33, 23, 39, 208, 144, 227, 13, 191, 165, 109, 208, 237 },
                            Role = 0
                        },
                        new
                        {
                            UserId = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 1, 23, 9, 4, 40, 338, DateTimeKind.Utc).AddTicks(8366),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Email = "Admin@gmail.com",
                            FullName = "Admin",
                            IsDeleted = false,
                            IsVerfied = true,
                            PasswordHash = new byte[] { 20, 186, 40, 69, 151, 146, 205, 52, 143, 136, 201, 126, 70, 113, 170, 152, 249, 208, 213, 240, 53, 108, 98, 52, 146, 139, 207, 97, 157, 84, 244, 81, 214, 10, 154, 3, 205, 240, 226, 52, 165, 135, 229, 255, 93, 153, 192, 124, 49, 164, 230, 159, 111, 136, 182, 51, 85, 8, 222, 252, 30, 219, 45, 238 },
                            PasswordSalt = new byte[] { 88, 160, 49, 100, 26, 88, 75, 140, 18, 56, 146, 239, 230, 49, 124, 176, 205, 235, 94, 73, 76, 129, 170, 19, 207, 156, 222, 46, 180, 250, 207, 77, 49, 17, 25, 187, 3, 53, 190, 234, 61, 252, 226, 211, 127, 20, 158, 161, 151, 10, 200, 156, 147, 108, 213, 85, 115, 145, 183, 89, 202, 214, 83, 39, 228, 149, 235, 236, 126, 95, 226, 198, 8, 71, 34, 92, 52, 137, 107, 231, 96, 5, 68, 157, 97, 82, 72, 132, 238, 138, 202, 125, 64, 25, 57, 165, 170, 79, 178, 113, 94, 235, 178, 165, 69, 77, 134, 108, 57, 83, 103, 58, 99, 183, 142, 43, 253, 237, 6, 152, 46, 112, 95, 160, 225, 197, 22, 110 },
                            Role = 0
                        });
                });

            modelBuilder.Entity("Domain.Entities.UserLessonProgress", b =>
                {
                    b.Property<Guid>("LessonProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CompletionPercent")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastWatchedSecond")
                        .HasColumnType("integer");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LessonProgressId");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId");

                    b.ToTable("UserLessonProgresses");
                });

            modelBuilder.Entity("Domain.Entities.AnswerOption", b =>
                {
                    b.HasOne("Domain.Entities.Question", "Question")
                        .WithMany("AnswerOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Domain.Entities.Enrollment", b =>
                {
                    b.HasOne("Domain.Entities.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Enrollments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.GradedAttempt", b =>
                {
                    b.HasOne("Domain.Entities.GradedItem", "GradedItem")
                        .WithMany("GradedAttempts")
                        .HasForeignKey("GradedAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("GradedAttempts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradedItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.GradedItem", b =>
                {
                    b.HasOne("Domain.Entities.Lesson", "Lesson")
                        .WithMany("GradedItems")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Domain.Entities.Lesson", b =>
                {
                    b.HasOne("Domain.Entities.Module", "Module")
                        .WithMany("Lessons")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Domain.Entities.LessonResource", b =>
                {
                    b.HasOne("Domain.Entities.Lesson", "Lesson")
                        .WithMany("LessonResources")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Domain.Entities.Module", b =>
                {
                    b.HasOne("Domain.Entities.Course", "Course")
                        .WithMany("Modules")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Domain.Entities.Payment", b =>
                {
                    b.HasOne("Domain.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Enrollment", "Enrollment")
                        .WithMany()
                        .HasForeignKey("EnrollmentId");

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Enrollment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Question", b =>
                {
                    b.HasOne("Domain.Entities.GradedItem", "GradedItem")
                        .WithMany("Questions")
                        .HasForeignKey("GradedItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradedItem");
                });

            modelBuilder.Entity("Domain.Entities.QuestionSubmission", b =>
                {
                    b.HasOne("Domain.Entities.GradedAttempt", "GradedAttempt")
                        .WithMany("QuestionSubmissions")
                        .HasForeignKey("GradedAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Question", "Question")
                        .WithMany("QuestionSubmissions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GradedAttempt");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Domain.Entities.SubmissionAnswerOption", b =>
                {
                    b.HasOne("Domain.Entities.AnswerOption", "AnswerOption")
                        .WithMany("SubmissionAnswerOptions")
                        .HasForeignKey("AnswerOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.QuestionSubmission", "QuestionSubmission")
                        .WithMany("SelectedOptions")
                        .HasForeignKey("QuestionSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnswerOption");

                    b.Navigation("QuestionSubmission");
                });

            modelBuilder.Entity("Domain.Entities.UserLessonProgress", b =>
                {
                    b.HasOne("Domain.Entities.Lesson", "Lesson")
                        .WithMany("UserLessonProgresses")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("UserLessonProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.AnswerOption", b =>
                {
                    b.Navigation("SubmissionAnswerOptions");
                });

            modelBuilder.Entity("Domain.Entities.Course", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Modules");
                });

            modelBuilder.Entity("Domain.Entities.GradedAttempt", b =>
                {
                    b.Navigation("QuestionSubmissions");
                });

            modelBuilder.Entity("Domain.Entities.GradedItem", b =>
                {
                    b.Navigation("GradedAttempts");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Domain.Entities.Lesson", b =>
                {
                    b.Navigation("GradedItems");

                    b.Navigation("LessonResources");

                    b.Navigation("UserLessonProgresses");
                });

            modelBuilder.Entity("Domain.Entities.Module", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("Domain.Entities.Question", b =>
                {
                    b.Navigation("AnswerOptions");

                    b.Navigation("QuestionSubmissions");
                });

            modelBuilder.Entity("Domain.Entities.QuestionSubmission", b =>
                {
                    b.Navigation("SelectedOptions");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("GradedAttempts");

                    b.Navigation("Payments");

                    b.Navigation("UserLessonProgresses");
                });
#pragma warning restore 612, 618
        }
    }
}
